name: Parameters build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./parameters

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true  # this caches installation but is only available on Linux x86-64 runners

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v6

        with:
          role-to-assume: ${{ secrets.PARAMETERS_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: SAM validate
        run: sam validate

      - name: SAM build and test
        run: sam build

      - name: Upload lambdas to S3
        env:
          ARTIFACT_BUCKET: ${{ secrets.PARAMETERS_ARTIFACT_SOURCE_BUCKET_NAME }}
          SIGNING_PROFILE: ${{ secrets.SIGNING_PROFILE }}
        run: sam package --s3-bucket="$ARTIFACT_BUCKET" --output-template-file=cf-template.yaml #--signing-profiles HelloWorldFunction="$SIGNING_PROFILE" HelloWorldFunction2="$SIGNING_PROFILE"

      - name: Zip the cloudformation template
        run: zip template.zip cf-template.yaml

      - name: Upload zipped cloudformation artifact to S3
        env:
          ARTIFACT_BUCKET: ${{ secrets.PARAMETERS_ARTIFACT_SOURCE_BUCKET_NAME }}
        run: aws s3 cp template.zip "s3://$ARTIFACT_BUCKET/template.zip" --metadata "repository=$GITHUB_REPOSITORY,commitsha=$GITHUB_SHA"
