name: SAM app deploy using Environment secrets
run-name: SAM app deploy using Environment secrets to ${{ inputs.environment }}

################################ Prerequisite setup ################################
# Set the customization template for an OpenID Connect (OIDC) subject claim for the repository.
# You must authenticate using an access token with the repo scope to curl the endpoint.
#
#        curl -L \
#          -X PUT \
#          -H "Accept: application/vnd.github+json" \
#          -H "Authorization: Bearer <YOUR-TOKEN>"\
#          -H "X-GitHub-Api-Version: 2022-11-28" \
#          https://api.github.com/repos/govuk-one-login/devplatform-demo-sam-app/actions/oidc/customization/sub \
#          -d '{"use_default":false,"include_claim_keys":["repo","context","ref"]}'
#
# With the above setup, example sub from AssumeRoleWithWebIdentity as seen in Cloudtrail in build account
#        "subjectFromWebIdentityToken": "repo:govuk-one-login/devplatform-demo-sam-app:environment:build:ref:refs/heads/main",

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        type: environment
        required: true
      check-secrets:
        description: |
          Uploads text file containing GHA Environment name into artifact source bucket
          This is used to find out which artifact source bucket a particular GHA Environment deploys to
        type: boolean
        default: false
        required: false
      upload-tests:
        description: Push tests to ECR (default is true)
        type: boolean
        default: true
        required: false

defaults:
  run:
    shell: bash
    working-directory: ./sam-app

jobs:
  check-secrets:
    if: ${{ inputs.check-secrets == true }} 
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.SAM_APP_GH_ACTIONS_ROLE_ARN || secrets.SAM_APP_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2
      - name: Check secrets
        run: |
          echo "environment=${ENVIRONMENT}" | tee -a environment.txt
          aws s3 cp environment.txt s3://${SAM_APP_ARTIFACT_BUCKET_NAME}/
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          SAM_APP_ARTIFACT_BUCKET_NAME: ${{ vars.SAM_APP_ARTIFACT_BUCKET_NAME || secrets.SAM_APP_ARTIFACT_BUCKET_NAME }}
        working-directory: .
          
  deploy:
    if: ${{ inputs.check-secrets == false }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 11
        uses: actions/setup-java@v5
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v5
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true  # this caches installation but is only available on Linux x86-64 runners

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.SAM_APP_GH_ACTIONS_ROLE_ARN || secrets.SAM_APP_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: SAM validate
        run: sam validate

      - name: SAM build and test
        run: sam build

      - name: Login to Amazon ECR
        if: ${{ inputs.upload-tests == true }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install Cosign
        if: ${{ inputs.upload-tests == true }}
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.5.3'

      - name: Build, tag, and push testing image to Amazon ECR
        if: ${{ inputs.upload-tests == true }}
        env:
          CONTAINER_SIGN_KMS_KEY: ${{ vars.CONTAINER_SIGN_KMS_KEY || secrets.CONTAINER_SIGN_KMS_KEY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.SAM_APP_ECR_REPOSITORY_BUILD || secrets.SAM_APP_ECR_REPOSITORY_BUILD }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          cosign sign --key awskms:///${CONTAINER_SIGN_KMS_KEY} $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          cosign sign --key awskms:///${CONTAINER_SIGN_KMS_KEY} $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action/sam@v4.1.0
        with:
            artifact-bucket-name: ${{ vars.SAM_APP_ARTIFACT_BUCKET_NAME || secrets.SAM_APP_ARTIFACT_BUCKET_NAME }}
            signing-profile-name: ${{ vars.SIGNING_PROFILE_NAME || secrets.SIGNING_PROFILE_NAME }}
            working-directory: ./sam-app/.aws-sam/build
