name: WAF for demo build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'node-with-waf/WAFv2/**'
      - '.github/workflows/waf-post-merge-actions.yml'

defaults:
  run:
    shell: bash
    working-directory: ./node-with-waf/WAFv2/

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cloudfront-estimate
    timeout-minutes: 60
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v3
        with:
          use-installer: true  # this caches installation but is only available on Linux x86-64 runners

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.WAF_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: SAM validate
        run: sam validate

      - name: SAM build and test
        run: sam build

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@v4.2.0
        with:
          artifact-bucket-name: ${{ secrets.WAF_ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: ./node-with-waf/WAFv2/.aws-sam/build
